/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.12-1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.an9elkiss.api.spp.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;

import com.an9elkiss.api.spp.command.TimeEntryCmd;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-04-28T09:59:07.066Z")

@Api(value = "time-entry", description = "the time-entry API")
public interface TimeEntryApi {


	@ApiOperation(value = "Finds time entry by id", nickname = "findTimeEntryById", notes = "Finds time entry by id", response = TimeEntryCmd.class, tags = {
			"time-entry", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = TimeEntryCmd.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied") })
	ResponseEntity<TimeEntryCmd> findTimeEntryById(
			@ApiParam(value = "ID of time entry that needs to be fetched", required = true) @PathVariable("id") Integer id);

}
